# Generated by Django 4.2 on 2024-10-12 08:55

from django.db import migrations, models
import planetarium_service.models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium_service", "0002_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="astronomyshow",
            options={"ordering": ["-title"]},
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
        migrations.AddField(
            model_name="planetariumdome",
            name="image",
            field=models.ImageField(
                null=True, upload_to=planetarium_service.models.movie_image_path
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("show_session", "row", "seat")},
        ),
    ]
